import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const buildResult = spawnSync(process.execPath, ['scripts/build.mjs'], { encoding: 'utf8' });
assert.equal(buildResult.status, 0, buildResult.stderr);
const loader = readFileSync('script.js', 'utf8');

test('build emits a small deterministic classic loader', () => {
  assert.match(loader, /GENERATED by scripts\/build\.mjs/);
  assert.ok(loader.length < 2000, `loader unexpectedly large: ${loader.length}`);
  assert.match(loader, /document\.createElement\('script'\)/);
  assert.doesNotMatch(loader, /MercaTaxDomain = Object\.freeze/);
});

test('loader preserves strict domain-before-app order and waits for DOM when needed', () => {
  const domainIndex = loader.indexOf("load('src/domain.js'");
  const appIndex = loader.indexOf("load('src/app.js'");
  assert.ok(domainIndex >= 0 && appIndex > domainIndex);
  assert.match(loader, /DOMContentLoaded/);
  assert.match(loader, /element\.async = false/);
});
