import { writeFileSync } from 'node:fs';

const loader = `/* GENERATED by scripts/build.mjs — edit source modules, not script.js. */
(function(){
'use strict';
const current=document.currentScript;
const baseUrl=current&&current.src?new URL('.',current.src):new URL('.',window.location.href);
function load(path,onload){const element=document.createElement('script');element.src=new URL(path,baseUrl).href;element.async = false;element.onload=onload;element.onerror=()=>{throw new Error('Failed to load '+path)};document.head.appendChild(element)}
function aux(path,onload){load(path,onload)}
function loadHomeCardRefinement(){aux('src/mobile-copy-r1.js',()=>aux('src/store-release-ui-r2.js',()=>aux('src/mobile-home-card-r2.js')))}
function start(){load('src/domain.js',()=>load('src/tax-remediation.js',()=>load('src/tax-calendar-contract.js',()=>load('src/tax-ui-bridge.js',()=>aux('src/runtime-state-compat.js',()=>load('src/app.js',()=>aux('src/runtime-unresolved-sale-guard.js',()=>load('src/mobile-r1-ui.js',()=>load('src/mobile-vnext-ui.js', loadHomeCardRefinement)))))))))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
}());
`;

writeFileSync('script.js', loader);
console.log('Generated compact certified core loader with Store Ready R2 presentation layers');
