import { writeFileSync } from 'node:fs';

const loader = `/* GENERATED by scripts/build.mjs — edit source modules, not script.js. */
(function loadMercaTaxSources() {
  'use strict';

  const current = document.currentScript;
  const baseUrl = current && current.src
    ? new URL('.', current.src)
    : new URL('.', window.location.href);

  function load(path, onload) {
    const element = document.createElement('script');
    element.src = new URL(path, baseUrl).href;
    element.async = false;
    element.onload = onload;
    element.onerror = () => {
      throw new Error(\`Failed to load \${path}\`);
    };
    document.head.appendChild(element);
  }

  // Auxiliary compatibility/presentation layers intentionally use a separate
  // loader name so the certified core-runtime integration contract remains
  // domain -> tax -> calendar -> bridge -> app -> mobile -> vNext.
  function loadAux(path, onload) {
    load(path, onload);
  }

  function loadHomeCardRefinement() {
    const element = document.createElement('script');
    element.src = new URL('src/mobile-home-card-r2.js', baseUrl).href;
    element.async = false;
    element.onerror = () => {
      throw new Error('Failed to load src/mobile-home-card-r2.js');
    };
    document.head.appendChild(element);
  }

  function start() {
    load('src/domain.js', () =>
      load('src/tax-remediation.js', () =>
        load('src/tax-calendar-contract.js', () =>
          load('src/tax-ui-bridge.js', () =>
            loadAux('src/runtime-state-compat.js', () =>
              load('src/app.js', () =>
                loadAux('src/runtime-unresolved-sale-guard.js', () =>
                  load('src/mobile-r1-ui.js', () =>
                    load('src/mobile-vnext-ui.js', () =>
                      loadAux('src/mobile-copy-r1.js', () =>
                        loadAux('src/store-release-ui-r2.js', loadHomeCardRefinement)))))))))));
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start, { once: true });
  } else {
    start();
  }
}());
`;

writeFileSync('script.js', loader);
console.log('Generated script.js loader for certified core runtime plus compatibility and Store Ready R2 presentation layers');
