import { writeFileSync } from 'node:fs';

const loader = `/* GENERATED by scripts/build.mjs — edit source modules, not script.js. */
(function loadMercaTaxSources() {
  'use strict';

  const current = document.currentScript;
  const baseUrl = current && current.src
    ? new URL('.', current.src)
    : new URL('.', window.location.href);

  function load(path, onload) {
    const element = document.createElement('script');
    element.src = new URL(path, baseUrl).href;
    element.async = false;
    element.onload = onload;
    element.onerror = () => {
      throw new Error(\`Failed to load \${path}\`);
    };
    document.head.appendChild(element);
  }

  function loadHomeCardRefinement() {
    const element = document.createElement('script');
    element.src = new URL('src/mobile-home-card-r2.js', baseUrl).href;
    element.async = false;
    element.onerror = () => {
      throw new Error('Failed to load src/mobile-home-card-r2.js');
    };
    document.head.appendChild(element);
  }

  function start() {
    load('src/domain.js', () =>
      load('src/tax-remediation.js', () =>
        load('src/tax-calendar-contract.js', () =>
          load('src/tax-ui-bridge.js', () =>
            load('src/runtime-state-compat.js', () =>
              load('src/app.js', () =>
                load('src/runtime-unresolved-sale-guard.js', () =>
                  load('src/mobile-r1-ui.js', () =>
                    load('src/mobile-vnext-ui.js', loadHomeCardRefinement)))))))));
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start, { once: true });
  } else {
    start();
  }
}());
`;

writeFileSync('script.js', loader);
console.log('Generated script.js loader for domain -> tax remediation -> certified calendar contract -> tax UI bridge -> persisted-state compatibility -> app -> unresolved-sale aggregate guard -> mobile UI -> vNext UI -> compact home summary refinement');
